name: sphinx

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    container:
      image: libmcu/sphinx
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fix git safe.directory in container
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Install dependencies
        run: |
          git clone https://github.com/libmcu/libmcu.git
          git clone https://github.com/libmcu/cbor.git
          git clone https://github.com/libmcu/firmware.git
          git clone https://github.com/libmcu/pwifi.git
          git clone https://github.com/libmcu/pble.git
          git clone https://github.com/libmcu/pmqtt.git
          git clone https://github.com/libmcu/pl4.git
          git clone https://github.com/libmcu/bq25180.git
          mkdir -p build/doxygen
      - name: Build
        run: LD_LIBRARY_PATH=$(llvm-config --libdir) make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/html

  deploy:
    name: Deploy to the github page
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
